/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#f9f9f9",
        "secondary": "#006d37",
        "surface-container-high": "#e8e8e8",
        "background": "#f9f9f9",
        "outline": "#7b7486",
        "on-secondary-fixed-variant": "#005228",
        "on-surface-variant": "#4a4455",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e2e2e2",
        "surface-container": "#eeeeee",
        "surface": "#f9f9f9",
        "outline-variant": "#ccc3d7",
        "tertiary-fixed": "#ffdbd1",
        "primary-fixed-dim": "#d2bcff",
        "tertiary-container": "#a52d00",
        "primary": "#5300b9",
        "on-primary-fixed": "#25005a",
        "secondary-container": "#6bfe9c",
        "on-tertiary-container": "#ffc1b0",
        "on-error": "#ffffff",
        "on-secondary-container": "#00743a",
        "on-primary-fixed-variant": "#5900c7",
        "inverse-surface": "#2f3131",
        "on-secondary-fixed": "#00210c",
        "primary-fixed": "#eaddff",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "surface-dim": "#dadada",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "surface-container-low": "#f3f3f3",
        "on-tertiary-fixed-variant": "#862300",
        "inverse-on-surface": "#f1f1f1",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#d2bcff",
        "tertiary-fixed-dim": "#ffb59f",
        "on-tertiary-fixed": "#3a0a00",
        "tertiary": "#7c2000",
        "surface-variant": "#e2e2e2",
        "surface-tint": "#7233df",
        "secondary-fixed-dim": "#4ae183",
        "on-primary-container": "#dac7ff",
        "primary-container": "#6c2bd9",
        "on-background": "#1a1c1c",
        "secondary-fixed": "#6bfe9c",
        "on-surface": "#1a1c1c"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
    },
  },
  plugins: [],
}
